#!/bin/bash
#
# Init script for mrepo distribution server.
#
# Written by Dag Wieers <dag@wieers.com>.
#
# chkconfig: 2345 90 10
# description: mrepo distribution server.
#
# processname: mrepo
# config: /etc/mrepo.conf

source /etc/rc.d/init.d/functions

[ -x /usr/bin/mrepo ] || exit 1

### Default variables
SYSCONFIG="/etc/sysconfig/mrepo"
YAMCONFIG="/etc/mrepo.conf"

### Read configuration
[ -r "$SYSCONFIG" ] && source "$SYSCONFIG"

[ -r "$YAMCONFIG" ] || exit 1

RETVAL=0
prog="mrepo"
desc="meepo Distribution Server"

start() {
	echo -n $"Starting $desc ($prog): "
	mrepo -q -c $YAMCONFIG
	RETVAL=$?
	[ $RETVAL -eq 0 ] && success || failure
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
	return $RETVAL
}

stop() {
	echo -n $"Shutting down $desc ($prog): "
	mrepo -q --umount -c $YAMCONFIG
	RETVAL=$?
	[ $RETVAL -eq 0 ] && success || failure
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
	return $RETVAL
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  reload)
	reload
	;;
  condrestart)
	[ -e /var/lock/subsys/$prog ] && restart
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|condrestart}"
	RETVAL=1
esac

exit $RETVAL
